dist: trusty
sudo: false

env:
  global:
    - PATH="~/bin:$PATH"
    - TERRAFORM_VERSION="0.11.8"

before_install:
  - curl -sLo "/tmp/terraform.zip" "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
  - unzip /tmp/terraform.zip -d /tmp
  - mkdir -p ~/bin
  - mv /tmp/terraform ~/bin
  - which terraform
  - terraform --version

script:
  - terraform init -backend=false
  - terraform validate
